### PR TITLE
Feature - Control Panel - add help text to Property tab of service page

### PR DESCRIPTION
**Pull request by ase174**
## Description

Added the following 'help text' to the left of the 'Edit Properties' button on the Service.js page:

"Before adding a community property to a service, ask yourself: ‘Does this organization/service have expertise and experience in serving this particular community?’ (Note: ‘We serve everyone’ does not count as demonstrated expertise for our purposes at InReach.)"

## Asana ticket:
https://app.asana.com/0/1132189118126148/1202588495993667

## PR Checklist

- [ ] Assign @trigal2012 **and** @Alfredo-Moreira as reviewers.
- [ ] If your PR is not a hotfix, is it targeted for `dev`? If your PR is a hotfix, is it targeted for `master`?
- [ ] Unit and functional test coverage was added where applicable.
- [ ] CI/CD passes for your PR.
- [ ] Complex code is well documented with comments.
- [ ] Does the original ticket have test instructions? If not add them below

## How to Test

In the control panel go to 'View' on an organization, under 'Services' press 'View', then go to the 'Properties' tab. At the top of the page, help text is now present left of the 'Edit Properties' button.

### CODE REVIEW

**Review by trigal2012 — CHANGES_REQUESTED** [review]
in the description, rather than showing a screen shot of the code, enter the help text. The help text is more meaningful to future users and coders than the code.

**Review by trigal2012 — CHANGES_REQUESTED** [review]
due to the additional code, the test coverage is now below the minimum required. Create a unit test to test that the help text is displayed.

**Review by trigal2012 — COMMENTED** [review]
the pacakage.json has your local changes. Please remove them.

**Comment by ase174** [comment]
I have reverted my package.json changes.

**Review by trigal2012 — APPROVED** [review]

**Pull request merged**
