### PR TITLE
Feature/1201788821943838/control panel user demographics

### PR DESCRIPTION
**Pull request by jrrlokken**
## Description

Implement user details view in Control Panel for data administrators.
Add 'View' link to user list
Add details modal, opens on 'View' click
View-only modal displays several fields of user details.

## PR Checklist

- [x] Assign @trigal2012 **and** @Alfredo-Moreira as reviewers.
- [x] If your PR is not a hotfix, is it targeted for `dev`? If your PR is a hotfix, is it targeted for `master`?
- [x] Unit and functional test coverage was added where applicable.
- [x] CI/CD passes for your PR.
- [x] Complex code is well documented with comments.
- [x] Does the original ticket have test instructions? If not add them below

## How to Test

Login to Control Panel, click on Admin in the navigation.
There is a list of users, each with a 'View' and 'Delete' link.
Click View next to any user to open a modal displaying user details.
Can close or cancel the modal only (read-only).

### CODE REVIEW

**Review by trigal2012 — CHANGES_REQUESTED** [review]
nice job getting this done.
Only change request I have is to make the fields not editable. In the modal that opens, a user can click into each field and change a value. Of course there is no way to save those changes(by design). It may be confusing to users giving them the impression that they should be able to make changes.

**Review by trigal2012 — APPROVED** [review]

**Review by Alfredo-Moreira — APPROVED** [review]

**Review by Alfredo-Moreira — CHANGES_REQUESTED** [review]
Be sure to have automation tests updated. Some of them are failing

**Review by Alfredo-Moreira — APPROVED** [review]
Automation updated

**Comment by Alfredo-Moreira** [comment]
> nice job getting this done. Only change request I have is to make the fields not editable. In the modal that opens, a user can click into each field and change a value. Of course there is no way to save those changes(by design). It may be confusing to users giving them the impression that they should be able to make changes.

I would recommend we create a story to address this.

**Pull request merged**
