### PR TITLE
Updated service coverage dialog

### PR DESCRIPTION
**Pull request by nathanial**
## Description

~Added typeahead behavior to the CoverageEdit dialog. I've solicited some feedback in the Asana ticket, so I'm marking this as a "Draft" PR for now, pending a response.~

This PR adds select boxes to the CoverageEdit dialog for picking Country, State, City, and County, plus a textbox for Towns. It also adds some static data files with lists states and cities by state for Mexico, Canada, and the US. 

- Asana ticket: https://app.asana.com/0/1132189118126148/1180818950425345

## How to Test
1. Go to the edit page for an organization or service
2. Edit the ServiceAreaCoverage using the new component
3. Verify that it saves correctly to the org or service

### CODE REVIEW

**Comment by ShehryarKh** [comment]
@nathanial any specific reason to choose to manually have added data?  We would need to reflect these changes in the catalog as well. There is a section that checks for if the service location is present in `src/utils/serviceAreaCoverage.json` in the catalog. Any thoughts on added the data files to that repo as well.. that would have been your next task anyway.

**Comment by ShehryarKh** [comment]
@nathanial maybe we remove that part of the code that checks for if the service location is present in that file. Ideally, a user would search for a location in the catalog the code will construct the service location string and just pass it over to the API.

**Comment by nathanial** [comment]
@ShehryarKh It sounds like removing the check would make the most sense. However I don't have a strong opinion either way. I also don't mind adding the data files in both places. The reason to add them to the frontend is just for convenience / avoiding any new API calls.

**Comment by ShehryarKh** [comment]
@nathanial It seems like if we remove that check in the catalog we don't need to add the data, Can you help determine where the check is happening in the catalog?

**Comment by nathanial** [comment]
@ShehryarKh Yes, I'll look into it this evening.

**Comment by nathanial** [comment]
@ShehryarKh Looks like the check is happening in the `fetchOrganizations` function of `asylumconnect-catalog/src/utils/api.js`. I'll submit a PR to remove that check, probably by Thursday at the latest.

**Pull request merged**
